### ISSUE TITLE
Refuel radius 

### ISSUE THREAD

**Issue by RobbiGB** [sercanatici/PrestigeRP-Suggestion#12]
Could you increase the refuel radius on a vehicle?
When going to a gas station you have to park your vehicle so close to be able to refuel, most of the time you have to shuffle to the over seat to get out just so it can be close enough. 

Just a small increase on this radius will make it better

**Comment by sercanatici** [comment]
I have not experienced this problem please remember that the back part of the vehicle needs to be close to the pump.
