### ISSUE TITLE
When using /reappear AI vehicles will spawn nearby

### ISSUE THREAD

**Issue by LxSKingJayJay** [sercanatici/PrestigeRP-Suggestion#18]
When someone dies near or on highway, when using /reappear
AI will spawn in a massive amount in a single location

To reproduce this:
1. go unconcious on the highway
2. might need others nearby to trigger
3. use /reappear

![20200918192451_1](https://user-images.githubusercontent.com/72012091/94412219-d324b180-0179-11eb-986b-e0deaf79bfe9.jpg)

**Comment by sercanatici** [comment]
This is caused by the actual game, in regards to the /reappear this will be removed soon as we implement the new ambulancejob script.
